
CREATE TABLE IF NOT EXISTS USUARIO (
  idCorreo VARCHAR(30) NOT NULL,
  correo VARCHAR(50) UNIQUE NOT NULL,
  nombre VARCHAR(50) NOT NULL,
  estado VARCHAR(30) NOT NULL,
  contrasena VARCHAR(65) NOT NULL,
  PRIMARY KEY (idCorreo));