
CREATE TABLE IF NOT EXISTS ROL (
  id INT NOT NULL DEFAULT NEXTVAL ('ROL_seq'),
  nombreRol VARCHAR(30) NOT NULL,
  PRIMARY KEY (id))
;

CREATE TABLE IF NOT EXISTS USUARIO (
  idCorreo VARCHAR(30) NOT NULL,
  correo VARCHAR(50) UNIQUE NOT NULL,
  nombre VARCHAR(50) NOT NULL,
  rol_id INT NOT NULL,
  estado VARCHAR(30) NOT NULL,
  contrasena VARCHAR(50) NOT NULL,
  PRIMARY KEY (idCorreo),
  CONSTRAINT fk_USUARIO_ROL
    FOREIGN KEY (rol_id)
      REFERENCES ROL (id))
;